### ISSUE TITLE
window.phet.neuron conflicts with PhET namespace convention

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/neuron#102]
In neuron-main.js:

```js
    // create a namespace for sim-specific globals
    window.phet.neuron = window.phet.neuron || {};
```

This conflicts with PhET's new convention for namespacing, where a subtype of phetCore.Namespace is used.  See for example color-vision.colorVision.js.

**Comment by jbphet** [comment]
Fixed, closing.
