### ISSUE TITLE
Potential chart does not plot if cleared while neuron is stimulated

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/neuron#104]
Test device: Mac Air, Jordan

Operating System: OS X 10.9.5

Browser: Safari 9.0.1 (9537.86.2.7.2)

Problem description: If the neuron is stimulated after the potential chart is full, then the chart is reset, nothing will be plotted. If you stimulate the neuron a second time, the chart will begin to plot. 

Steps to reproduce: Run sim so that potential chart is full. Stimulate neuron. Clear potential chart. 

Severity:

Screenshots: 
https://drive.google.com/file/d/0B_TAL-jnJOoKUndRY1VNRDhaOEU/view?usp=sharing

Troubleshooting information (do not edit):
Name: ‪Neuron‬
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.1/neuron_en.html
Version: 1.0.0-rc.1 2015-12-22 23:06:19 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/537.86.2
Language: en-us
Window: 1264x598
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.28.36)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"6f3c2e01","branch":"HEAD"},"babel":{"sha":"9618fad2","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"1d1d5d32","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"griddle":{"sha":"3adb78bd","branch":"HEAD"},"joist":{"sha":"191b15a4","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"neuron":{"sha":"3b7eee9d","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"47143cdd","branch":"HEAD"},"scenery-phet":{"sha":"a7f975d1","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"64555735","branch":"HEAD"},"tandem":{"sha":"07fbe58c","branch":"HEAD"}}

**Comment by arouinfar** [comment]
Also observed in OS X 10.11.2 on all browsers.

**Comment by jbphet** [comment]
I compared this behavior to that of the Java sim, and the Java sim will record the data after simulating the neuron and then immediately clearing the chart.  Assigning to myself to fix.

**Comment by jbphet** [comment]
This appears to have been some code that was simply missed in the porting process.  The ```NeuronModel``` was not being placed into the record state if an action potential was in progress when the chart was cleared.  I've added the code to do this, and did it to match the way in which it was done within the original Java simulation.

**Comment by jbphet** [comment]
Should be fixed, will leave this issue open until verified on v1.0.0-rc.2.

**Comment by jbphet** [comment]
Assigning to @ariel-phet so that he or someone on the QA team can verify that this is fixed on v1.0.0-rc.2 (http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.2/neuron_en.html).

**Comment by ariel-phet** [comment]
Made checklist item for https://github.com/phetsims/tasks/issues/485

**Comment by elisemorgan** [comment]
This issue is resolved
