### ISSUE TITLE
Simulation runs slow with WebGL disabled on Microsoft Edge

### ISSUE THREAD

**Issue by bryo5363** [phetsims/neuron#107]
Test device: Acer Aspire R13 (Bryan's Personal Computer)

Operating System: Windows 10 64-bit

Browser: Microsoft Edge 25.10586.0.0

Problem description: With WebGL disabled, the simulation runs much slower than disabling WebGL on other browsers.

Steps to reproduce:

Severity:

Screenshots:

Troubleshooting information (do not edit):

Name: ‪Neuron‬

URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.1/neuron_en.html?webgl=false

Version: 1.0.0-rc.1 2015-12-22 23:06:19 UTC

Features missing: touch

Flags: pointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

Language: en-US

Window: 1280x603

Pixel Ratio: 1.5/1

WebGL: WebGL 0.96

GLSL: WebGL GLSL ES 0.96

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"6f3c2e01","branch":"HEAD"},"babel":{"sha":"9618fad2","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"1d1d5d32","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"griddle":{"sha":"3adb78bd","branch":"HEAD"},"joist":{"sha":"191b15a4","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"neuron":{"sha":"3b7eee9d","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"47143cdd","branch":"HEAD"},"scenery-phet":{"sha":"a7f975d1","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"64555735","branch":"HEAD"},"tandem":{"sha":"07fbe58c","branch":"HEAD"}}

**Comment by jbphet** [comment]
It is not particularly surprising that the performance isn't great with WebGL disabled.  After all, that's why we took the time to create the WebGL particle layers in the first place - to improve the simulation's performance.  So I don't particularly feel like any action is necessary on this, but I'll assign to @ariel-phet to make sure that he concurs.

**Comment by ariel-phet** [comment]
agreed @jbphet, I don't think any action is necessary, Webgl should generally work with Edge, unless the graphics card is black listed (you would think that would be less likely with Win 10 computers).
