### ISSUE TITLE
Sim does not rewind once potential plot is full

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/neuron#110]
Test device: iPad 2, Tycho

Operating System: iOS 9.2 13C75

Browser: Safari

Problem description: Once the potential plot has been filled, rewinding the sim changes nothing on the screen. 

Steps to reproduce: Complete potential chart. Pause sim and press rewind button. 

Severity:

Screenshots: Screen recording from Mac OS X 10.9.5
https://drive.google.com/file/d/0B_TAL-jnJOoKWUY4ZEt3VW1nNFk/view?usp=sharing

Troubleshooting information (do not edit):
Name: ‪Neuron‬
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.1/neuron_en.html
Version: 1.0.0-rc.1 2015-12-22 23:06:19 UTC
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 IMGSGX543-124.1)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"6f3c2e01","branch":"HEAD"},"babel":{"sha":"9618fad2","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"1d1d5d32","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"griddle":{"sha":"3adb78bd","branch":"HEAD"},"joist":{"sha":"191b15a4","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"neuron":{"sha":"3b7eee9d","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"47143cdd","branch":"HEAD"},"scenery-phet":{"sha":"a7f975d1","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"64555735","branch":"HEAD"},"tandem":{"sha":"07fbe58c","branch":"HEAD"}}

**Comment by jbphet** [comment]
Good catch.  The correct behavior, based on how the Java sim works, would be that the first backwards step moves the cursor to the end of the recorded data, which is at the end of the chart.  That's clearly not happening here.  I'll fix it.

**Comment by jbphet** [comment]
Assigning to @ariel-phet so that he or someone on the QA team can verify that this is fixed on v1.0.0-rc.2 (http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.2/neuron_en.html).

**Comment by ariel-phet** [comment]
made checklist item for https://github.com/phetsims/tasks/issues/485

**Comment by elisemorgan** [comment]
This issue is resolved on iPad 2
