### ISSUE TITLE
Frozen ions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/neuron#115]
@jbphet the "free floating" ions that in general casually float around will instead be frozen in place if you do this:

1. Zoom in if you want to see the ions clearer.
2. Open the potential chart, then un-check All Ions.
3. Stimulate the neuron!
4. Wait until the sim allows you to re-check All Ions...and re-check it.
5. Drag the potential line back, and you'll notice that the now enabled free floating ions are frozen in place. Once the potential chart reaches the point where you dragged it back, they will start moving again.

Video, with fast forward enabled just so the video was less boring:
https://drive.google.com/file/d/0B3HJopSo_QqLOFQ2cEl0aW1wdDQ/view?usp=sharing

Seen on 1.0.0-rc.2 with Win 8.1 Chrome. For phetsims/tasks/issues/485

Troubleshooting information:
Name: ‪Neuron‬
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.2/neuron_en.html
Version: 1.0.0-rc.2 2016-01-23 00:14:48 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"6f3c2e01","branch":"HEAD"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"1d1d5d32","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"griddle":{"sha":"3adb78bd","branch":"HEAD"},"joist":{"sha":"191b15a4","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"neuron":{"sha":"d5e13134","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"47143cdd","branch":"HEAD"},"scenery-phet":{"sha":"a7f975d1","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"64555735","branch":"HEAD"},"tandem":{"sha":"07fbe58c","branch":"HEAD"}}

**Comment by jbphet** [comment]
The "free floating" ions are *always* still during playback.  This was also true for the Java sim and has never been reported as an issue.  This is a good observation, but changing the behavior would be a pretty major overhaul, and since it matches the Java simulation's behavior and hasn't been a problem. I'm going to close this one and leave the sim as is.
