### ISSUE TITLE
Concentrations don't reset

### ISSUE THREAD

**Issue by phet-steele** [phetsims/neuron#117]
@jbphet, concentrations do not reset after doing a reset all. Stimulate the neuron and let the concentrations change before resetting, then you'll see the issue. Pretty simple.

Seen on most every platform we test with.....for phetsims/tasks/issues/509.

Troubleshooting information:
Name: ‪Neuron‬
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.3/neuron_en.html
Version: 1.0.0-rc.3 2016-02-09 23:56:54 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0
Language: en-US
Window: 1600x767
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"6f3c2e01","branch":"HEAD"},"babel":{"sha":"1f0156c5","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"1d1d5d32","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"griddle":{"sha":"3adb78bd","branch":"HEAD"},"joist":{"sha":"191b15a4","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"neuron":{"sha":"afa0dd78","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"47143cdd","branch":"HEAD"},"scenery-phet":{"sha":"a7f975d1","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"64555735","branch":"HEAD"},"tandem":{"sha":"07fbe58c","branch":"HEAD"}}

**Comment by elisemorgan** [comment]
Also seen on iPad

**Comment by jbphet** [comment]
This should now be fixed.  The model values were actually being reset, but the readouts weren't being updated because they had been optimized to only update when visible, and when the reset occurs it makes them invisible before the values are cleared.  I fixed this by forcing updates to the concentration readouts when they transition from invisible to visible.

**Comment by phet-steele** [comment]
@jbphet looks fixed on 1.0.0-rc.5!

**Comment by jbphet** [comment]
@phet-steele reports fixed, closing.
