### ISSUE TITLE
Stimulating after the chart completes instantiates more stimuli than desired

### ISSUE THREAD

**Issue by phet-steele** [phetsims/neuron#118]
@jbphet this may not be the *most* pressing bug due to how it's caused, but here it is:

Stimulating the neuron after the potential chart has gone its full length results in an interesting effect where the the channel proteins open before a second stimulus arrives. This involves manipulating the time state of the sim (pressing pause/play and rewind).

Steps:
1. Open the potential chart and stimulate the neuron to start the chart.
2. Let the chart play to its end, then a little after the drag-able line thing has left the chart stimulate the neuron again (~3 secs? It really doesn't matter).
3. Just as the stimulus arrives and the gates are opened, all the ions will begin rushing in and out. Pause the sim at this moment.
4. Use the backwards step button until the drag-able line thing appears at the end of the chart (shouldn't it only take one click?).
5. Play the sim. The sim will proceed forward in time to the place where we paused it when the gates were open, then follow up with a second stimulus coming from seemingly nowhere.

Video (file too big for a gif). Ignore the bad performance, it was a consequence of my screen recorder:
https://drive.google.com/file/d/0B3HJopSo_QqLbWhkRmFlV3loRk0/view?usp=sharing

Tested on Win 10 browsers (my computer) and Chromebook (Chadwick). For phetsims/tasks/issues/509.

Troubleshooting information:
Name: ‪Neuron‬
URL: http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-rc.3/neuron_en.html
Version: 1.0.0-rc.3 2016-02-09 23:56:54 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Language: en-US
Window: 1600x775
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"6f3c2e01","branch":"HEAD"},"babel":{"sha":"1f0156c5","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"1d1d5d32","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"griddle":{"sha":"3adb78bd","branch":"HEAD"},"joist":{"sha":"191b15a4","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"neuron":{"sha":"afa0dd78","branch":"HEAD"},"phet-core":{"sha":"73a034c6","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"47143cdd","branch":"HEAD"},"scenery-phet":{"sha":"a7f975d1","branch":"HEAD"},"sherpa":{"sha":"be8c4fc9","branch":"HEAD"},"sun":{"sha":"64555735","branch":"HEAD"},"tandem":{"sha":"07fbe58c","branch":"HEAD"}}

**Comment by phet-steele** [comment]
@jbphet molto bene!

**Comment by jbphet** [comment]
Sounds like the fix is confirmed.  Closing.
