### ISSUE TITLE
Create Design Doc

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/neuron#121]
@elisemorgan I recently realized that Neuron lacks a design doc. As you have done in the past, can you create one that lays out the old java sim and some screenshots of the HTML5 sim documenting some of the changes made?

Once you have made the doc, please assign this issue back to me.

Unfortunately, this sim proceeded in a very nontraditional fashion because another University payed a third party to port the sim, so we did not really follow the normal process, but I figure it would be best to get things as much in line with our normal workflow as possible, so thanks for your help!

**Comment by ariel-phet** [comment]
And of course feel free to use another doc as a template

**Comment by ariel-phet** [comment]
Note for myself - I will try to see if I can gather any legacy information.

**Comment by ariel-phet** [comment]
Original design doc here:

https://docs.google.com/document/d/1RE5wWCPA6GORY_8bGI2_VMJWyaLQGVARJgtTNvEgWn8/edit

When @elisemorgan has created the new doc, I will distill the learning goals and such from the old doc.

**Comment by elisemorgan** [comment]
HTML5 Design doc is complete
https://docs.google.com/document/d/1us5zeyKuutUDfhRhQT8CJQ0IIrhFsm_AtBRdq3U0nGw/edit?usp=sharing

**Comment by ariel-phet** [comment]
@elisemorgan can you give me edit privileges on the doc and make phethelp@gmail the owner?

**Comment by elisemorgan** [comment]
Done
