### ISSUE TITLE
screenshot doesn't work on current release branch

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#125]
I am currently in the process of making the screenshot capability available without a query parameter for all sims, see https://github.com/phetsims/chipper/issues/475.  On the currently released branch of the Neuron sim, which is 1.0, the screenshot feature doesn't work.  This is probably due to the fact that it uses a WebGL node, and the ability to get screenshots from WebGL nodes has, I think, only recently been added.  The problem can be easily replicated on version http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.4-rc.1/neuron_en.html.  Simply start the sim, take a screenshot, and you'll see that none of the ions are visible in the resulting image.

I just tested this on master, and the screenshot feature works fine.  Probably the easiest way to resolve this issue would be to just do a new RC branch and release off of master.  This would require roughly an hour or two of developer time and a fair amount of QA time to do a full test cycle, so I will assign to @ariel-phet to decide whether this should be done.

**Comment by ariel-phet** [comment]
Yes, go ahead with releases off master and move ahead with RC testing as mentioned in  phetsims/bending-light#350

**Comment by phet-steele** [comment]
It's working!
