### ISSUE TITLE
adjust touchArea options for HSlider thumb 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/neuron#127]
In https://github.com/phetsims/sun/issues/254, the touchArea defaults for HSlider thumb were changed so that they default to pixels, not a percentage of the thumb size.  Sims that use HSlider's `thumbSize` option will therefore need to also specify `thumbTouchAreaXDilation` and `thumbTouchAreaYDilation`.

**Comment by jbphet** [comment]
I adjusted the touch area for the slider knob to pretty much match the currently live version, though I ended up making it a little bit wider.  While working on this, I noticed that the zoom in/out buttons also had touch areas that had changed from the currently live version, so I adjusted them as well.

That should do it.  Closing.
