### ISSUE TITLE
recording starts running immediately instead of waiting for stimulus

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#136]
On the current master version, the recording appears to start right away instead of waiting until the user pushes the "Stimulate Neuron" button.

My guess is that this was introduced when this sim was moved off of Property Set, see https://github.com/phetsims/axon/issues/102.

Assigning to @Denz1994, since he did the conversion.

**Comment by Denz1994** [comment]
After talking with @jbphet on this issue, I figured out what property was not being set.

Essentially, it was ```modeProperty.get(mode)``` when it should have been ```modeProperty.set(mode)```. Thank you for the summary of how the sim should behave with by reviewing the published version.
