### ISSUE TITLE
gates are not opening and closing

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#137]
On the current master version, the sodium and potassium gates are not opening and closing when the action potential reaches the cross section.  I suspect this is related to the recent conversion away from PropertySet, see https://github.com/phetsims/axon/issues/102.

Assigning to @Denz1994, since he did the conversion.

**Comment by Denz1994** [comment]
The gates now open and close as intended. I am going to close this as this was reviewed with @jbphet.
