### ISSUE TITLE
JSDoc should include types and descriptions in @param annotations

### ISSUE THREAD

**Issue by samreid** [phetsims/neuron#14]
The JSDoc is valuable to indicate the purpose and intended usage of each function.  Some of the functions and constructors in neuron are missing type annotations and description of the function/constructor and the parameters.  For instance, in ZoomControl.js the constructor is declared as such:

```js
  /**
   * @param  neuronModel
   * @param  zoomProperty
   * @param  minZoom
   * @param  maxZoom
   * @constructor
   */

  function ZoomControl( neuronModel, zoomProperty, minZoom, maxZoom ) {
```

Please add the parameter types and a description for each.  I'll fix this case shortly as a demonstration, but if there are other cases in the code that need improved JSDoc, they should be addressed.  Discovered during #1.

**Comment by jbphet** [comment]
Done on master and on the 1.0 branch, closing.
