### ISSUE TITLE
incorrect inherit call in MembranePotentialChart.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/neuron#145]
Noted while working on https://github.com/phetsims/tasks/issues/1049.

In the MembranePotentialChart.js,  Node superclass constructor is call, but inherit is using Panel.  Node appears to be the proper superclass.

```js
function MembranePotentialChart( chartDimension, neuronClockModelAdapter ) {

  const self = this;
  Node.call( this );
...
}
...
inherit( Panel, MembranePotentialChart, {
```

**Comment by pixelzoom** [comment]
Fixed in the above commit.  @jbphet please review.

**Comment by jbphet** [comment]
Looks good to me, thanks.  Closing.
