### ISSUE TITLE
Is slice necessary here?

### ISSUE THREAD

**Issue by samreid** [phetsims/neuron#147]
From a TODO in https://github.com/phetsims/axon/issues/279

```js
this.transientParticlesBackup.addAll( this.transientParticles.slice() ); // TODO: https://github.com/phetsims/axon/issues/279 is slice necessary here?
```

Assigning to responsible dev.

**Comment by jbphet** [comment]
No, I don't believe the call to `slice` is needed.  The `addAll` method uses the spread operator, so no additional copy of the array is necessary.

I verified that the functionality was correct after removing the call to `slice` by stimulating the neuron with the potential chart visible and periodically grabbing the playback marker and moving it backwards in time.  I used `console.log` to verify that the code above was being called.  It all seemed to work fine.

Closing.
