### ISSUE TITLE
Credits need to be added

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#23]
No credits are currently shown in the Neuron sim - they should be added.

**Comment by jbphet** [comment]
We're getting close to moving this sim through the publication process.  I think the credits are done, but I'll assign to @ariel-phet to have one last look to make sure they seem correct.

**Comment by ariel-phet** [comment]
@jbphet please move @amanda-phet to lead design, but otherwise looks good.

**Comment by jbphet** [comment]
@amanda-phet is now listed as one of the lead designers.  Closing.
