### ISSUE TITLE
Particle WebGL resolution should be increased

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/neuron#46]
The particles look quite pixelated on my screen, and increasing the resolution should fix it. #45 should be done first, since increasing the texture size may have negative performance implications.

An example particle on my screen:
![neuron-particle](https://cloud.githubusercontent.com/assets/480878/5366486/496fa01c-7fb1-11e4-841f-f89f7494d1e1.png)

**Comment by jbphet** [comment]
This was addressed when working on #65, closing.
