### ISSUE TITLE
NeuronModel should inherit from RecordAndPlaybackModel, not ParticleCapture

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#54]
In the Java code, NeuronModel extended RecordAndPlaybackModel and implemented the IParticleCapture interface.  In the ported JavaScript version, there is a ParticleCapture class that inherits from RecordAndPlaybackModel, and NeuronModel then inherits from ParticleCapture.  While this works, it's a bit hard to figure out the workings of the JavaScript code when it's structured this way.  NeuronModel should be made to inherit directly from RecordAndPlaybackModel, and it should just implement the needed interface.

If we choose to make the ported code more JavaScript-ish, we can pass the capture method to all of the membrane channels instead of the entire model, as is done now, and was done in Java as type IParticleCapture.

**Comment by AshrafSharf** [comment]
NeuronModel now directly inherits from RecordAndPlayBackModel.

**Comment by jbphet** [comment]
Changes look good, and it eliminates a nice chunk of unneeded code. Closing.
