### ISSUE TITLE
Charges and concentrations are not being updated in playback mode

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#59]
The charge and concentration values are not updated when doing playback.  They definitely are in the Java version, so this appears to have been introduced during the port.  This can be duplicated on version http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.8/neuron_en.html.

**Comment by AshrafSharf** [comment]
I can see the values being updated to concentration values and to "charges symbol" during playback.
@jbphet would like to discuss it today

**Comment by jbphet** [comment]
Behavior now looks correct.  Thanks.  Closing.
