### ISSUE TITLE
Port the WebGL portions to be compatible with Scenery 0.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#65]
Our original plan for getting Neuron published was to have it use the 0.1 branch of Scenery.  That's not working out so well, since other libraries are starting to get dependent on Scenery 0.2 (see #61).  Also, being dependent on the 0.1 version is likely to create long term maintenance issues for this sim.  @samreid and @jonathanolson and I have discussed this, and we think it is possible to port the portions of the code that uses WebGL to Scenery 0.2.  @jonathanolson has created some demos and done some prepatory work for this.

**Comment by jonathanolson** [comment]
@jbphet, let me know if you need anything else for transparency. I believe the issues are fixed in ParticlesWebGLNode5.

**Comment by jbphet** [comment]
The work on this has been completed, closing.
