### ISSUE TITLE
use PhetColorScheme.RED_COLORBLIND ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/neuron#68]
This sim has several red UI elements, currently defined using 'red', Color.RED, or `RED_COLOR_BUFFER_DATA = [ 0.7, 0, 0 ]`.  Evaluate whether some of these should be using PhetColorScheme.RED_COLORBLIND.

**Comment by jbphet** [comment]
I've changed most usages of red to use the color blind version, but will leave this open to remind me to verify that the WebGL particles also use it once that effort is complete, see #65.

**Comment by jbphet** [comment]
All values used to render particles and lines (such as on the chart) are now using PhetColorScheme.RED_COLORBLIND.  There are a few places where other values of red exist in the code, but these are vestigial and will be gone once the WebGL node is finalized.  At this point, I think it's safe to close this issue.
