### ISSUE TITLE
Potassium ions are appearing outside of the clipped area

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#7]
When zoomed all the way in, the potassium ions that are going into and out of the potassium leak channel on the far right of the clipped area are visible outside of the area.  Please see the highlighted areas in the screen shots below.

![neuron-potassium-ions-off-edge](https://cloud.githubusercontent.com/assets/3082831/4777175/67518dc0-5bcb-11e4-8352-78cc81284853.png)

![neuron-potassium-ions-off-edge-2](https://cloud.githubusercontent.com/assets/3082831/4777177/6da556a2-5bcb-11e4-9f12-d0a18f6ba595.png)

**Comment by samreid** [comment]
@jbphet mentioned he will be resuming work on neuron and its webgl implementation soon, I'll send this his way.

**Comment by jbphet** [comment]
I've adjusted the size of the border shape to hide the largest particles, and it appears to be working well.  Closing.
