### ISSUE TITLE
Fast Forward and Slow Motion don't work when playing back recorded data

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#88]
If the simulation is rewound and playback is started, and then the speed is set to Fast Forward or Slow Motion, the speed of playback doesn't change.  Once the end of the playback is reached (as evidenced by the chart cursor on the potential chart reaching the end of the recorded data), the simulation starts operating at the set speed.  This behavior is present on the current master and on the most recent dev release, which is http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.13/neuron_en.html.  I haven't bisected to figure out exactly when this appeared, but I see that it was *not* present on 1.0.0-dev.9.

**Comment by ariel-phet** [comment]
Fixed in 1.0.0-rc.1

Closing
