### ISSUE TITLE
Step backwards isn't working quite right

### ISSUE THREAD

**Issue by jbphet** [phetsims/neuron#9]
The highlighted area in the screenshot below shows a potassium ion inside the cell membrane near a leak channel.  This state was achieved by running the sim normally until a potassium ion went through the channel and then changed direction, hitting the pause button, and stepping backwards.  The ion travels in a straight line along its return path rather than turning and going back through the channel.

I tried this same sequence in the Java simulation, and it doesn't behave perfectly there either, so it's possible that this is a bug that was never detected and that was propagated during the port.  The behavior is a little different in this case - there is a big jump where the potassium ion returns to the mouth of the gated channel, then things work okay.  It's possible that this was intentionally saved as the last viable state - I honestly don't recall.

![neuron-potassium-ion-in-membrane](https://cloud.githubusercontent.com/assets/3082831/4777273/39274910-5bcd-11e4-830a-a4a2127e80af.png)

**Comment by AshrafSharf** [comment]
With the change made to StepBack behaviour  related #26,now it is not possible to do a stepBack without stimulating the neuron. So this issue cannot be reproduced

**Comment by jbphet** [comment]
I verified that this can no longer be reproduced.  Closing.
